version: '3.8'

services:
  stock-api:
    build: .
    container_name: stock-api-app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: 192.168.3.3
      DB_PORT: 5433
      DB_NAME: stock
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: 192.168.3.3
      REDIS_PORT: 6379
      REDIS_DB: 0
    restart: unless-stopped