"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2026-03-23 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_cn_history_market',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('trade_date', sa.Date(), nullable=False),
        sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('volume', sa.BigInteger(), nullable=True),
        sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('turnover', sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column('amplitude', sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column('change_rate', sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column('change_amount', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('ma5', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('ma10', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('ma20', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('ma60', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('macd_dif', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('macd_dea', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('macd_hist', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code', 'trade_date', name='_code_trade_date_uc')
    )
    op.create_index(op.f('ix_stock_cn_history_market_code'), 'stock_cn_history_market', ['code'], unique=False)
    op.create_index(op.f('ix_stock_cn_history_market_trade_date'), 'stock_cn_history_market', ['trade_date'], unique=False)
    op.create_index('idx_stock_history_code_date', 'stock_cn_history_market', ['code', 'trade_date'], unique=False)
    op.create_index('idx_stock_history_date', 'stock_cn_history_market', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_history_date', table_name='stock_cn_history_market')
    op.drop_index('idx_stock_history_code_date', table_name='stock_cn_history_market')
    op.drop_index(op.f('ix_stock_cn_history_market_trade_date'), table_name='stock_cn_history_market')
    op.drop_index(op.f('ix_stock_cn_history_market_code'), table_name='stock_cn_history_market')
    op.drop_table('stock_cn_history_market')
    # ### end Alembic commands ###
