"""Create stock_choose_strategy table

Revision ID: 002
Revises: 001
Create Date: 2026-03-25 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_choose_strategy',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('value', JSON(), nullable=False),
        sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='_name_uc')
    )
    # Insert default strategy data
    op.execute("""
        INSERT INTO stock_choose_strategy (name, value, status)
        VALUES (
            '中等风险',
            '{\"min_change_rate\": 3.0, \"max_change_rate\": 6.0, \"min_market_cap\": 50, \"max_market_cap\": 800, \"check_ma20\": true, \"check_macd\": true, \"check_recent_rise\": true, \"recent_days\": 3}'::json,
            'active'
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_choose_strategy')
    # ### end Alembic commands ###
