"""Create stock_best_choose table

Revision ID: 003
Revises: 002
Create Date: 2026-03-25 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON


# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_best_choose',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('scan_date', sa.Date(), nullable=False),
        sa.Column('choose_reason', JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_best_choose_code'), 'stock_best_choose', ['code'], unique=False)
    op.create_index(op.f('ix_stock_best_choose_scan_date'), 'stock_best_choose', ['scan_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_best_choose_scan_date'), table_name='stock_best_choose')
    op.drop_index(op.f('ix_stock_best_choose_code'), table_name='stock_best_choose')
    op.drop_table('stock_best_choose')
    # ### end Alembic commands ###
